--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rover17-Dev/Contact-Info-Plugin-Pocketmine
build-by-default: true
branches:
- main
projects:
  Contact-Info-Plugin-Pocketmine:
    path: ""
...
