---
name: SocialMediaInfo
version: 1.0.1
main: Rover17\SocialMediaInfo\Main
api: 5.0.0
commands:
  info:
    description: See our server socials links
    permission: socialmediainfo.info.cmd
  discord : 
    description: See our discord link
    permission: socialmediainfo.discord.cmd

permissions:
  socialmediainfo.info.cmd:
    description: Permission to use discord command
    default: true
  socialmediainfo.discord.cmd:
    description: Permission to use info command
    default: true
...
