---
name: SocialMediaInfo
version: 1.0.0
main: Rover17\SocialMediaInfo\Main
api: 4.0.0
commands:
  info:
    description: See our server socials links
    permission: info.cmd
discord : 
    description: See our discord link
    permission: discord.cmd

permissions:
  info.cmd:
    description: Permission to use discord command
    default: true
  discord.cmd:
    description: Permission to use info command
    default: true
...
