---
name: SocialMediaInfo
version: 1.0.0
main: Rover17\SocialMediaInfo\Main
api: 4.0.0
commands:
  info:
    description: See our server socials links
discord : 
    description: See our discord link

...
