# BasicContactInfo 
# This plugin is fully configurable

#The message for the /discord command
discord: "ยง3Our server discord : Your discord link"

#Infos 
#The messages for the /info commands
Ligne1: "ยง1 Our discord : "
Ligne2: "ยง1 Our teamspeak :"
Ligne3: "ยง41 Our site :"


#Plugin by Rover17 
#Updates will be realise soon
