# SocialMediaInfo
# This plugin is fully configurable


#Infos 
#The messages for the /info commands
Line1: "ยง1 Our discord : "
Line2: "ยง1 Our teamspeak :"
Line3: "ยง41 Our site :"


#Plugin by Rover17 
#Updates will be realise soon
