# SocialMediaInfo
# This plugin is fully configurable
#  ___          _      _ __  __        _ _      ___       __     
# / __| ___  __(_)__ _| |  \/  |___ __| (_)__ _|_ _|_ _  / _|___ 
# \__ \/ _ \/ _| / _` | | |\/| / -_) _` | / _` || || ' \|  _/ _ \
# |___/\___/\__|_\__,_|_|_|  |_\___\__,_|_\__,_|___|_||_|_| \___/
#                                                                

#Infos 
#The messages for the /info commands
Line1: "ยง1 Our discord : "
Line2: "ยง1 Our teamspeak :"
Line3: "ยง1 Our site :"

#Discord 
Discord: "Our discord : discord.gg/link"

#Plugin by Rover17 
#Updates will be realised soon
